// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwOD68T4JjvVDwmByOD6y6R68PTYQGPn8',
    appId: '1:1068059627876:web:910f900e2de8d117eaea71',
    messagingSenderId: '1068059627876',
    projectId: 'realtimedatabase-9b1d4',
    authDomain: 'realtimedatabase-9b1d4.firebaseapp.com',
    databaseURL: 'https://realtimedatabase-9b1d4-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-9b1d4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6gmgHUgPvOV1UjnGstNTVRNv89SMW5Pc',
    appId: '1:1068059627876:android:c3d8b6e2c881d82beaea71',
    messagingSenderId: '1068059627876',
    projectId: 'realtimedatabase-9b1d4',
    databaseURL: 'https://realtimedatabase-9b1d4-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-9b1d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjW-0Wg75d-zxdgtDZ9-zBlP29McQtTsk',
    appId: '1:1068059627876:ios:2f36bb13c83e7b42eaea71',
    messagingSenderId: '1068059627876',
    projectId: 'realtimedatabase-9b1d4',
    databaseURL: 'https://realtimedatabase-9b1d4-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-9b1d4.appspot.com',
    iosBundleId: 'com.example.realtimeApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjW-0Wg75d-zxdgtDZ9-zBlP29McQtTsk',
    appId: '1:1068059627876:ios:96015370068c940aeaea71',
    messagingSenderId: '1068059627876',
    projectId: 'realtimedatabase-9b1d4',
    databaseURL: 'https://realtimedatabase-9b1d4-default-rtdb.firebaseio.com',
    storageBucket: 'realtimedatabase-9b1d4.appspot.com',
    iosBundleId: 'com.example.realtimeApplication.RunnerTests',
  );
}
